# Test against the latest version of this Node.js version
environment:
  nodejs_version: "7"
  NPM_TOKEN:
    secure: p6I7IcfVWhufrMLBwgQ2OQgMA/65tmLwryPmVr+zbRGpSUB/Kq/JPP/MSWmPNutQ
  matrix:
    - GYP_MSVS_VERSION: "2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GYP_MSVS_VERSION: "auto"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GYP_MSVS_VERSION: ""
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GYP_MSVS_VERSION: "2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - GYP_MSVS_VERSION: "auto"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - GYP_MSVS_VERSION: ""
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - GYP_MSVS_VERSION: "2013"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - GYP_MSVS_VERSION: "2012"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - GYP_MSVS_VERSION: "2010"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#the official config for deploy
    - GYP_MSVS_VERSION: "2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017


matrix:
  fast_finish: true


init:
  - ps: >-
      & { Echo "GYP_MSVS_VERSION='$env:GYP_MSVS_VERSION'" };

      if (($env:GYP_MSVS_VERSION -ge 2012) -and ($env:GYP_MSVS_VERSION -lt 2015)) {
        $env:SKIP_NODE_GYP="1"
      };

      if (($env:APPVEYOR_REPO_TAG -eq 'true') -and ($env:GYP_MSVS_VERSION -eq 2017) -and ($env:APPVEYOR_IMAGE -eq 2017))
      {
        $env:SHOULD_PUBLISH="1"
      };


install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: >-
      npm config set "//registry.npmjs.org/:_authToken=%NPM_TOKEN%" -q

      SET NPM_TOKEN=

      md C:\projects\windows-autoconf\logs

      npm -g install mocha > nul

      npm link

      tools\try_powershell.cmd > C:\projects\windows-autoconf\logs\vs-output.json

      cd C:\projects & git clone https://github.com/node4good/gyp.js.git

      cd C:\projects\gyp.js & npm link windows-autoconf & npm i > nul 2> nul

      cd C:\projects & git clone https://github.com/refack/node-gyp.git

      cd C:\projects\node-gyp & npm link windows-autoconf & npm i > nul

      cd C:\projects & git clone https://github.com/refack/build.git boost.build


build: off


test_script:
- cmd: >-
    cd C:\projects\windows-autoconf

    npm test 2> C:\projects\windows-autoconf\logs\windows-autoconf_err.log

- ps: >-
    cd C:\projects\boost.build;

    $s = Get-Content .\bootstrap.bat | select -Skip 1;

    $s | Set-Content .\bootstrap.bat;

    $s = Get-Content .\src\engine\build.bat | select -Skip 1;

    $s | Set-Content .\src\engine\build.bat;

    .\bootstrap.bat 2> C:\projects\windows-autoconf\logs\bootstrap_err.log

    if (!(Test-Path bjam.exe)) {throw}

- cmd: >-
    cd C:\projects\boost.build

    copy "C:\projects\boost.build\bootstrap.log" "C:\projects\windows-autoconf\logs\"

    cd test\test2

    ..\..\bjam 2> C:\projects\windows-autoconf\logs\bjam_err.log;

- cmd: >-
    IF NOT SKIP_NODE_GYP=1 cd C:\projects\node-gyp & npm test 2> C:\projects\windows-autoconf\logs\node-gyp_err.log

- cmd: >-
    cd C:\projects\gyp.js

    mocha 2> C:\projects\windows-autoconf\logs\gyp_js_err.log


deploy_script:
- cmd: >-
    IF SHOULD_PUBLISH==1 npm publish


on_finish:
- ps: >-
    cd C:\projects\windows-autoconf\logs\;

    Get-Item *.* | %{ Push-AppveyorArtifact $_.FullName}
